version: '3.5'

services:
  elasticsearch:
    image : dataesr/es_icu:1.0
    environment:
      - "discovery.type=single-node"

    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

volumes:
  elastic:
