services:
  redis:
    image: redis:5.0.7-alpine
    networks:
      - affiliation-matcher-network

  dashboard:
    image: dataesr/dashboard-crawler:1.1
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - affiliation-matcher-network
    depends_on:
      - redis

  elasticsearch:
    image: dataesr/es_icu:7.12.0
    ports:
      - 9200:9200
    environment:
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - affiliation-matcher-network

  worker:
    build: .
    privileged: true
    command: >
      /bin/sh -c "sysctl -w vm.max_map_count=262144
      && python3 manage.py run_worker"
    environment:
      APP_SETTINGS: project.server.config.DevelopmentConfig
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    networks:
      - affiliation-matcher-network
    depends_on:
      - redis
      - elasticsearch

  web:
    build: .
    privileged: true
    ports:
      - 5004:5000
    command: python3 manage.py run -h 0.0.0.0
    environment:
      FLASK_DEBUG: 1
      APP_SETTINGS: project.server.config.DevelopmentConfig
      APP_ENV: 'development'
      ODS_KEY: ${ODS_API_KEY}
      ES_PAYSAGE_URL: ${ES_PAYSAGE_URL}
      ES_PAYSAGE_TOKEN: ${ES_PAYSAGE_TOKEN}
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    networks:
      - affiliation-matcher-network
    depends_on:
      - worker

networks:
  affiliation-matcher-network:
    driver: bridge

volumes:
  elastic:
