services:
  redis:
    image: redis:5.0.7-alpine
    networks:
      - matcher-network

  dashboard:
    image: dataesr/dashboard-crawler:1.1
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - matcher-network
    depends_on:
      - redis

  elasticsearch:
    image: dataesr/es_icu:1.1
    ports:
      - 9200:9200
    environment:
      - 'discovery.type=single-node'
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - matcher-network

  worker:
    image: dataesr/matcher:0.0.9
    privileged: true
    command: >
      /bin/sh -c "sysctl -w vm.max_map_count=262144
      && python3 manage.py run_worker"
    environment:
      APP_SETTINGS: matcher.server.config.DevelopmentConfig
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    networks:
      - matcher-network
    depends_on:
      - redis
      - elasticsearch

  web:
    image: dataesr/matcher:0.0.9
    privileged: true
    ports:
      - 5004:5000
    command: python3 manage.py run -h 0.0.0.0
    environment:
      DATAESR_HEADER: 'cm9vdDp0b25uZXJyZTJCcmVzdA=='
      FLASK_DEBUG: 1
      APP_SETTINGS: matcher.server.config.DevelopmentConfig
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    networks:
      - matcher-network
    depends_on:
      - worker

networks:
  matcher-network:
    driver: bridge

volumes:
  elastic:
