FROM python:3.8.0-alpine

WORKDIR /src

COPY requirements_cron.txt /src/requirements.txt
COPY cron.py /src/.

RUN pip3 install --upgrade pip
RUN     pip3     install -r requirements.txt --proxy=${HTTP_PROXY}

