version: '3.5'

services:
  elasticsearch:
    image : dataesr/es_icu:1.0
    environment:
      - "discovery.type=single-node"

    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - dash-network
    ports:
      - '9200:9200'

  matcher-web:
    image: dataesr/matcher:latest
    privileged: true
    ports:
      - 5004:5000
    command: python3 manage.py run -h 0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=matcher.server.config.DevelopmentConfig
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    networks:
      - dash-network
    depends_on:
      - redis
  
  matcher-worker:
    image: dataesr/matcher:latest
    privileged: true
    command: /bin/sh start.sh
    environment:
      - APP_SETTINGS=matcher.server.config.DevelopmentConfig
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    networks:
      - dash-network
    depends_on:
      - redis

  redis:
    image: redis:5.0.7-alpine
    networks:
      - dash-network

  dashboard:
    image: dataesr/dashboard-crawler:1.0
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - dash-network
    depends_on:
      - redis
networks:
  dash-network:
    driver: bridge

volumes:
  elastic:
